from setuptools import setup

setup(
    name='Dengame1',
    version='1.0',
    packages=['venv.Lib.distutils', 'venv.Lib.encodings', 'venv.Lib.importlib', 'venv.Lib.collections',
              'venv.Lib.site-packages.pip', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.idna', 'venv.Lib.site-packages.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip._vendor.certifi', 'venv.Lib.site-packages.pip._vendor.chardet',
              'venv.Lib.site-packages.pip._vendor.chardet.cli', 'venv.Lib.site-packages.pip._vendor.distlib',
              'venv.Lib.site-packages.pip._vendor.distlib._backport', 'venv.Lib.site-packages.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip._vendor.urllib3', 'venv.Lib.site-packages.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip._internal', 'venv.Lib.site-packages.pip._internal.req',
              'venv.Lib.site-packages.pip._internal.vcs', 'venv.Lib.site-packages.pip._internal.utils',
              'venv.Lib.site-packages.pip._internal.models', 'venv.Lib.site-packages.pip._internal.commands',
              'venv.Lib.site-packages.pip._internal.operations', 'venv.Lib.site-packages.past',
              'venv.Lib.site-packages.past.tests', 'venv.Lib.site-packages.past.types',
              'venv.Lib.site-packages.past.utils', 'venv.Lib.site-packages.past.builtins',
              'venv.Lib.site-packages.past.translation', 'venv.Lib.site-packages.cocos',
              'venv.Lib.site-packages.cocos.audio', 'venv.Lib.site-packages.cocos.audio.SDL',
              'venv.Lib.site-packages.cocos.audio.pygame', 'venv.Lib.site-packages.cocos.layer',
              'venv.Lib.site-packages.cocos.scenes', 'venv.Lib.site-packages.cocos.actions',
              'venv.Lib.site-packages.wheel', 'venv.Lib.site-packages.wheel.tool',
              'venv.Lib.site-packages.wheel.signatures', 'venv.Lib.site-packages.future',
              'venv.Lib.site-packages.future.moves', 'venv.Lib.site-packages.future.moves.dbm',
              'venv.Lib.site-packages.future.moves.html', 'venv.Lib.site-packages.future.moves.http',
              'venv.Lib.site-packages.future.moves.test', 'venv.Lib.site-packages.future.moves.urllib',
              'venv.Lib.site-packages.future.moves.xmlrpc', 'venv.Lib.site-packages.future.moves.tkinter',
              'venv.Lib.site-packages.future.tests', 'venv.Lib.site-packages.future.types',
              'venv.Lib.site-packages.future.utils', 'venv.Lib.site-packages.future.builtins',
              'venv.Lib.site-packages.future.backports', 'venv.Lib.site-packages.future.backports.html',
              'venv.Lib.site-packages.future.backports.http', 'venv.Lib.site-packages.future.backports.test',
              'venv.Lib.site-packages.future.backports.email', 'venv.Lib.site-packages.future.backports.email.mime',
              'venv.Lib.site-packages.future.backports.urllib', 'venv.Lib.site-packages.future.backports.xmlrpc',
              'venv.Lib.site-packages.future.standard_library', 'venv.Lib.site-packages.pygame',
              'venv.Lib.site-packages.pygame.docs', 'venv.Lib.site-packages.pygame.gp2x',
              'venv.Lib.site-packages.pygame.tests', 'venv.Lib.site-packages.pygame.tests.test_utils',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests.all_ok',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests.exclude',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests.timeout',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests.failures1',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests.everything',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests.incomplete',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests.print_stderr',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests.print_stdout',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests.infinite_loop',
              'venv.Lib.site-packages.pygame.tests.run_tests__tests.incomplete_todo',
              'venv.Lib.site-packages.pygame.threads', 'venv.Lib.site-packages.pygame.examples',
              'venv.Lib.site-packages.pyglet', 'venv.Lib.site-packages.pyglet.gl', 'venv.Lib.site-packages.pyglet.app',
              'venv.Lib.site-packages.pyglet.font', 'venv.Lib.site-packages.pyglet.libs',
              'venv.Lib.site-packages.pyglet.libs.x11', 'venv.Lib.site-packages.pyglet.libs.win32',
              'venv.Lib.site-packages.pyglet.libs.darwin', 'venv.Lib.site-packages.pyglet.libs.darwin.cocoapy',
              'venv.Lib.site-packages.pyglet.text', 'venv.Lib.site-packages.pyglet.text.formats',
              'venv.Lib.site-packages.pyglet.image', 'venv.Lib.site-packages.pyglet.image.codecs',
              'venv.Lib.site-packages.pyglet.input', 'venv.Lib.site-packages.pyglet.media',
              'venv.Lib.site-packages.pyglet.media.drivers', 'venv.Lib.site-packages.pyglet.media.drivers.pulse',
              'venv.Lib.site-packages.pyglet.media.drivers.openal',
              'venv.Lib.site-packages.pyglet.media.drivers.directsound', 'venv.Lib.site-packages.pyglet.media.sources',
              'venv.Lib.site-packages.pyglet.media.sources.ffmpeg_lib', 'venv.Lib.site-packages.pyglet.canvas',
              'venv.Lib.site-packages.pyglet.window', 'venv.Lib.site-packages.pyglet.window.xlib',
              'venv.Lib.site-packages.pyglet.window.cocoa', 'venv.Lib.site-packages.pyglet.window.win32',
              'venv.Lib.site-packages.pyglet.window.carbon', 'venv.Lib.site-packages.pyglet.extlibs',
              'venv.Lib.site-packages.pyglet.graphics', 'venv.Lib.site-packages.certifi',
              'venv.Lib.site-packages.mp3play', 'venv.Lib.site-packages.telegram',
              'venv.Lib.site-packages.telegram.ext', 'venv.Lib.site-packages.telegram.files',
              'venv.Lib.site-packages.telegram.games', 'venv.Lib.site-packages.telegram.utils',
              'venv.Lib.site-packages.telegram.inline', 'venv.Lib.site-packages.telegram.vendor',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.util',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.contrib',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.packages',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.packages.backports',
              'venv.Lib.site-packages.telegram.vendor.ptb_urllib3.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.telegram.payment', 'venv.Lib.site-packages.setuptools',
              'venv.Lib.site-packages.setuptools.extern', 'venv.Lib.site-packages.setuptools._vendor',
              'venv.Lib.site-packages.setuptools._vendor.packaging', 'venv.Lib.site-packages.setuptools.command',
              'venv.Lib.site-packages.libfuturize', 'venv.Lib.site-packages.libfuturize.fixes',
              'venv.Lib.site-packages.libpasteurize', 'venv.Lib.site-packages.libpasteurize.fixes',
              'venv.Lib.site-packages.pkg_resources', 'venv.Lib.site-packages.pkg_resources.extern',
              'venv.Lib.site-packages.pkg_resources._vendor', 'venv.Lib.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='Vyazovoy Denis',
    author_email='indikv@list.ru',
    description='', install_requires=['pycurl']
)
